### ISSUE TITLE
Deleting a collection via REST yields NullpointerException

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm#150]
During the creation of UnitTests which involved the building of versions i noticed that the invocation of DELETE on 'rest/collection/<id>' resulted in a Nullpointer Exception for collections that actually contained built versions. The problem was caused by line 143 in de.fraunhofer.abm.app.controllers.CollectionController.deleteCollection. In this line the Hermes-Results are being deleted.

![nullpointer_abm_delete_collection](https://user-images.githubusercontent.com/37844219/40621603-d299f8d8-629d-11e8-9c8f-1cd38043ab09.png)

**Stacktrace:** 
java.lang.NullPointerException
	at de.fraunhofer.abm.app.controllers.CollectionController.deleteCollection(CollectionController.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at osgi.enroute.rest.simple.provider.RestMapper$Function.invoke(RestMapper.java:242)
	at osgi.enroute.rest.simple.provider.RestMapper.execute(RestMapper.java:393)
	at osgi.enroute.rest.simple.provider.RestServlet.service(RestServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at de.fraunhofer.abm.app.auth.RequestDelayFilter.doFilter(RequestDelayFilter.java:45)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at de.fraunhofer.abm.app.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:43)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:124)
	at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at

**Comment by ankur-1989** [comment]
@johannesduesing 
when are you getting this error?

So When I follow the below steps - 
1. Create a collection and then delete the collection - no error found
2. Create a collection followed by building a collection and then delete the build version - no error found.
3. Create a collection followed by building a collection and then unfreeze the collection and then delete the collection - no error found.

Could you please let me know the steps to reproduce the error?
Thanks

**Comment by johannesduesing** [comment]
For me this happens when executing the following steps: 
1. Create a new collection (I needed a sample program that successfully compiles for testing, used this: https://github.com/jenkins-docs/simple-java-maven-app\) 
2. Build that collection and wait for the build to succeed
3. Execute GetLatestSuccessfullyBuiltVersion on that collection (that is what i was testing)
4. Delete that collection

I fixed that error by using HttpClient.put(<collection>) in order to unfreeze the collection. Is it intended that this NullPointerException is thrown when deleting a frozen collection ?

**Comment by johannesduesing** [comment]
I added that function, which was request in #83, in PR #153. The function is implemented here:
https://github.com/ABenchM/abm/blob/ae0c1cc23efb456eadb42fe74ac31455b89e8dff/bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java#L154-L188
