### ISSUE TITLE
Define and implement user profile DB schema as per proposed goal

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#161]
concrete description is to be added soon.
for now, refer the respective goal's description in design document

**Comment by Chinmay-92** [comment]
We need two fields in DB for forgot/reset password feature
1. resetToken - encoded String value
2. expiredPeriod - duration in seconds

(more details about the same feature implementation can be found at [issue163](https://github.com/ABenchM/abm/issues/163)

**Comment by anitha181992** [comment]
1)I have made the changes to the database in the branch https://github.com/ABenchM/abm/tree/anitha_patch1
2)I have even made the changes to save the email address to the database.
@Chinmay-92 : You can try to access the email address and let me know.

**Comment by Chinmay-92** [comment]
@anitha181992 
I am facing some issue while testing the code inside your branch:
![error_email](https://user-images.githubusercontent.com/2173927/43726968-f70a96a2-99a0-11e8-93f8-61d2df0e6edd.png)

logs ->
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 550 Unknown user: test@uni-paderborn.de

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1607)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:887)
	at javax.mail.Transport.send0(Transport.java:191)
	at javax.mail.Transport.send(Transport.java:120)
	at de.fraunhofer.abm.app.controllers.UserController.postUsername(UserController.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at osgi.enroute.rest.simple.provider.RestMapper$Function.invoke(RestMapper.java:242)
	at osgi.enroute.rest.simple.provider.RestMapper.execute(RestMapper.java:393)
	at osgi.enroute.rest.simple.provider.RestServlet.service(RestServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at de.fraunhofer.abm.app.auth.RequestDelayFilter.doFilter(RequestDelayFilter.java:45)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at de.fraunhofer.abm.app.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:48)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:124)
	at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 Unknown user: test@uni-paderborn.de

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1458)
	... 40 more


Please provide steps to test it.
( I clicked on register and entered email id but getting exception for any email id)

**Comment by Chinmay-92** [comment]
We figured out the issue,
It was coming because of wrong email config in cnf project.

**Comment by anitha181992** [comment]
Merged the code changes to abmpg branch.
Hence closing the issue
